name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init - Dev
        working-directory: environments/dev
        run: terraform init -backend=false

      - name: Terraform Validate - Dev
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Init - Prod
        working-directory: environments/prod
        run: terraform init -backend=false

      - name: Terraform Validate - Prod
        working-directory: environments/prod
        run: terraform validate