name: Terraform CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: terraform-hybrid-landing-zone
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true

jobs:

  # =========================
  # DEV PLAN
  # =========================

  terraform-plan-dev:
    name: Terraform Plan - Dev
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init - Dev
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Validate - Dev
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan - Dev
        working-directory: environments/dev
        run: terraform plan -input=false -lock-timeout=5m


  # =========================
  # PROD PLAN
  # =========================

  terraform-plan-prod:
    name: Terraform Plan - Prod
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init - Prod
        working-directory: environments/prod
        run: terraform init

      - name: Terraform Validate - Prod
        working-directory: environments/prod
        run: terraform validate

      - name: Terraform Plan - Prod
        working-directory: environments/prod
        run: terraform plan -input=false -lock-timeout=5m


  # =========================
  # DEV APPLY
  # =========================

  terraform-apply-dev:
    name: Terraform Apply - Dev

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs:
      - terraform-plan-dev
      - terraform-plan-prod

    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init - Dev
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Apply - Dev
        working-directory: environments/dev
        run: terraform apply -auto-approve -input=false -lock-timeout=5m
